name: 构建

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: 构建
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置Go环境
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: true

      - name: 缓存Go模块
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: 安装xcaddy
        run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

      - name: 构建Caddy与插件
        run: |
          xcaddy build \
            --with github.com/stupidloud/caddy_ratelimit=.

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: caddy-with-ratelimit
          path: ./caddy
